# Generated by Django 6.0.2 on 2026-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=150, verbose_name='Содержимое')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Превью (изображение)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(verbose_name='Признак публикации')),
                ('number_of_views', models.IntegerField(verbose_name='Количество просмотров')),
            ],
        ),
    ]
