# Generated by Django 6.0.2 on 2026-02-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_record_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='number_of_views',
            field=models.IntegerField(null=True, verbose_name='Количество просмотров'),
        ),
    ]
