# Generated by Django 6.0.2 on 2026-02-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_record_number_of_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Превью (изображение)'),
        ),
    ]
