# Generated by Django 6.0.2 on 2026-02-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='number_of_views',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
